Unhandled exception
tumcms/Open-Infra-Platform pull request #110
Opened 2020-05-01 18:14 UTC by pjanck

Expanded the IfcGeometryConverter with an Exception for unsupported entities. This should now sufficiently cover the refactor.

2020-05-01 18:14 UTC, pjanck commented
Fixes #24 .

2020-05-08 16:11 UTC, hechth commented on Core/src/IfcGeometryConverter/UnhandledException.h
> +#define UNHANDLED_REPRESENTATION_EXCEPTION_H
Please use better include guards in the future.

2020-05-08 16:13 UTC, hechth approved these changes

2020-05-08 16:13 UTC, hechth commented on EarlyBinding/src/EXPRESS/EXPRESSEntity.h
> -	const std::string getErrorLog() const {
Why did you remove this?

2020-05-08 17:42 UTC, hechth requested changes
Please also incorporate the newest changes on development in the commits and re-pose the pull request

2020-05-08 19:13 UTC, pjanck commented on EarlyBinding/src/EXPRESS/EXPRESSEntity.h
> -	const std::string getErrorLog() const {
It was moved to EXPRESSObject

2020-05-12 06:33 UTC, merged