[REF] UnitConverter.h
tumcms/Open-Infra-Platform pull request #182
Opened 2020-07-15 17:14 UTC by SamuilsRulovs

- Replaced std::shared_ptr with EXPRESSReference
- included "EXPRESS/EXPRESSReference.h" library
- Added InconsistentModellingExceptions

2020-07-15 17:33 UTC, pjanck requested changes
There are some `.lock()` function calls in the file. Since you've changed the functions to now take `EXPRESSReference` instead of `std::shared_ptr`, these can be almost everywhere removed.

2020-07-15 17:33 UTC, pjanck commented on Core/src/IfcGeometryConverter/UnitConverter.h
> +
Leave it as it was. This exception is already handled in `setIfcProject`.

2020-07-15 17:33 UTC, pjanck commented on Core/src/IfcGeometryConverter/UnitConverter.h
> +					}
Similar to above.

2020-07-17 15:16 UTC, SamuilsRulovs commented on Core/src/IfcGeometryConverter/UnitConverter.h
> +
Resolved: e854d00

2020-07-17 15:16 UTC, SamuilsRulovs commented on Core/src/IfcGeometryConverter/UnitConverter.h
> +					}
Resolved: e854d00

2020-07-20 10:19 UTC, pjanck approved these changes

2020-07-20 10:19 UTC, merged