Include official IFC4X1 example files in testdata.
tumcms/Open-Infra-Platform pull request #27
Opened 2020-04-14 08:43 UTC by SamuilsRulovs

I have added in the folder “IFC4x1ExampleFiles”  folder “official”, where are staged all data from the  link below: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/link/annex-e.htm
I have staged all files just as how they are staged on the website: 

- [ ] E2_Basic_geometric_shape
- [ ] E3_Advanced_geometric_shape
- [ ] E4_Tessellated_shape
- [ ] E5_Tessellated_shape_with_style
- [ ] E6_Mapped_geometric_shape
- [ ] E7_Placements_and_GIS_referencing
- [ ] E8_Building_element_standard_case
- [ ] E9_Building_element_elemented_case
- [ ] E10_Building_element_configuration
- [ ] E11_Building_service_element
- [ ] E12_Structural_analysis_model
- [ ] E13_Construction_scheduling
- [ ] E14_Additional_test_cases
- [ ] E15_Alignment

2020-04-14 15:20 UTC, pjanck requested changes
Contact me if comments are not clear.

2020-04-14 15:20 UTC, pjanck commented on testdata/IFC4x1ExampleFiles/official/E10_Building_element_configuration/wall-with-opening-and-window.ifc
> +#15= IFCSIUNIT($,.LENGTHUNIT.,.MILLI.,.METRE.);
Most of the example files provided by buildingSMART have a mistake here. This should be corrected for all IFCSIUNIT-s in all files.
```suggestion
#15= IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
```

2020-04-14 15:20 UTC, pjanck commented on testdata/IFC4x1ExampleFiles/official/E15_Alignment/terrain-and-alignment.ifc
> +#19= IFCTRIANGULATEDFACESET(#24,$,.F.,((1,3,2),(1,3,2),(1,3,2),(4,6,5),(4,6,5),(4,6,5),(7,9,8),(7,9,8),(7,9,8),(10,12,11),(10,12,11),(10,12,11),(13,15,14),(13,15,14),(13,15,14),(16,18,17),(16,18,17),
Every triangle is included three times.

2020-04-14 15:20 UTC, pjanck commented on testdata/IFC4x1ExampleFiles/official/E15_Alignment/terrain-and-alignment.ifc
> +#21= IFCTRIANGULATEDFACESET(#26,$,.F.,((1,3,2),(1,3,2),(1,3,2),(4,6,5),(4,6,5),(4,6,5),(7,9,8),(7,9,8),(7,9,8),(10,12,11),(10,12,11),(10,12,11),(13,15,14),(13,15,14),(13,15,14),(16,18,17),(16,18,17),
Here as well, every triangle is included three times.

2020-04-14 15:20 UTC, pjanck commented on testdata/IFC4x1ExampleFiles/official/E5_Tessellated_shape_with_style/tessellation-with-image-texture.ifc
> +#56= IFCIMAGETEXTURE(.T.,.T.,'TEXTURE',#57,$,'C:\\dev\\Constructivity\\Constructivity.Renderer.Mono\\Textures\\diagnostic.png');
This path is absolute ...

2020-04-15 04:46 UTC, hechth approved these changes

2020-04-15 09:52 UTC, pjanck approved these changes

2020-04-15 09:53 UTC, merged