Curver converter documentation
tumcms/Open-Infra-Platform pull request #298
Opened 2020-12-18 11:43 UTC by SamuilsRulovs

2020-12-18 11:45 UTC, SamuilsRulovs commented
Unfortunately it was not jet possible to create an nested numbered list. I am looking for solution to this.

2020-12-18 11:52 UTC, pjanck commented
Nested numbering:

1. item
    1. with additional spaces
        1. you can achieve
        2. different levels
              1. of numbering
        3. got it?

2020-12-18 11:56 UTC, pjanck requested changes

2020-12-18 11:56 UTC, pjanck commented on Documentation/markdown/IfcGeometryConverter/CurveConverterDocumenetation.md
> +This short guide shows you which functions are included in CurveConverter.h
Please include also the full path to the file

2020-12-18 11:56 UTC, pjanck commented on Documentation/markdown/IfcGeometryConverter/CurveConverterDocumenetation.md
> +# CurveConverter.h Documentation
filename typo?

2020-12-25 12:35 UTC, SamuilsRulovs commented
I guess this pull request is not necessary anymore, since all information is in the Doxymentation

2020-12-25 12:35 UTC, closed without merging