Comments unit test
tumcms/Open-Infra-Platform pull request #30
Opened 2020-04-15 09:31 UTC by hechth

Started implementing unit tests for files.
* Started comment feature unit test.

2020-04-15 10:13 UTC, pjanck requested changes
Small changes to the example file requested in order to cover two additional possibilities of comments within an IFC file.

2020-04-15 10:13 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/Comments/Data/csg-primitive-commented.ifc
> +#10= IFCSIUNIT($,.LENGTHUNIT.,.MILLI.,.METRE.);
This is wrong in the official example files.
```suggestion
#10= IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);

2020-04-15 10:13 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/Comments/Data/csg-primitive-commented.ifc
> +#20= IFCSIUNIT($,.PLANEANGLEUNIT.,$,.RADIAN.);
See above.

2020-04-15 10:13 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/Comments/Data/csg-primitive-commented.ifc
> +*/
I would love to see an inline comment within an entity to complete the test. 
Sth like #77 = ENTITY (... /* comment */ , content,... );

2020-04-15 10:13 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/Comments/Data/csg-primitive-commented.ifc
> +// This time this is correct!
Add a comment at the end of some line with content as well.
Sth like #77 = ENTITY( content ); // This is a comment

2020-04-15 10:17 UTC, pjanck commented
Goes with #30 .

2020-04-16 07:59 UTC, hechth commented
Fixed bugs in the file, test case succeeds now.

2020-04-16 08:14 UTC, hechth commented
More work will be done in the future following #31

2020-04-16 08:17 UTC, pjanck approved these changes

2020-04-16 08:19 UTC, merged

2020-04-16 09:24 UTC, pjanck commented
Resolves #20 .