Fixing #350
tumcms/Open-Infra-Platform pull request #430
Opened 2021-04-18 13:19 UTC by SamuilsRulovs

Fixes #350

2021-04-19 06:17 UTC, pjanck requested changes

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
This should stay commented out.

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
This should stay commented out.

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
This should stay commented out.

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Similarly.

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Similarly.

2021-04-19 06:17 UTC, pjanck commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Similarly.

2021-04-22 08:41 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
Resolved: 2ad6aa0

2021-04-22 08:43 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
Resolved: 2ad6aa0

2021-04-22 08:43 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/basin-tessellation/src/basin-tessellation.cpp
> +
Resolved: 2ad6aa0

2021-04-22 08:43 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Resolved: 2ad6aa0

2021-04-22 08:43 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Resolved: 2ad6aa0

2021-04-22 08:43 UTC, SamuilsRulovs commented on UnitTests/Schemas/IFC4X1/bath-csg-solid/src/bath-csg-solid.cpp
> +
Resolved: 2ad6aa0

2021-04-22 09:50 UTC, pjanck approved these changes
LFTM.

2021-04-22 09:50 UTC, merged